### PR TITLE
Implement the update function of Report

### PR DESCRIPTION
**Pull request by nuitsjp**
Implement the update function of Report ( #18 )

### CODE REVIEW

**Comment by nuitsjp** [comment]
I would like to implement the next Issue #19  in this countermeasure.
This is because OnNavigatedTo is not called with the back button.

**Comment by nuitsjp** [comment]
Mission completed!
Please review.

**Comment by nuitsjp** [comment]
Marge completed for "Implement Azure LoginService #41".
Plese review.

**Comment by nuitsjp** [comment]
Done!
Please ReReview.

**Comment by nuitsjp** [comment]
Sorry.
I implemented it because SaveAsync at the time of update was not implemented yet.
Please ReReview.

**Comment by runceel** [comment]
I think so good!

Please merge.

**Pull request merged**
