### PR TITLE
Implementation of report registration function Unit Test #20

### PR DESCRIPTION
**Pull request by nuitsjp**

### CODE REVIEW

**Comment by nuitsjp** [comment]
Done. Please review!

**Comment by nuitsjp** [comment]
Fixed error caused by DateTime.Today when over date.
Please review.

**Comment by nuitsjp** [comment]
Modify DateTime.Today to testable.

**Comment by runceel** [comment]
Perfect!

**Comment by ytabuchi** [comment]
Great works!!! Thank you!

**Pull request merged**
