### PR TITLE
Add LoginPage 

### PR DESCRIPTION
**Pull request by runceel**
Add LoginPage #36

### CODE REVIEW

**Comment by runceel** [comment]
Complete!!

Please review.

**Comment by nuitsjp** [comment]
I like to set readonly when field set in the constructor is not changed after that.

- LoginPageViewModel#_navigationService
- LoginPageViewModel#_loginServic
- LoginPageViewModel#_pageDialogService

And "_loginServic" is typo.

**Comment by runceel** [comment]
Add readonly and fix typo.

Please ReReview.

**Comment by nuitsjp** [comment]
Perfect! It is a great job!

**Comment by ytabuchi** [comment]
LoginPageViewModelTest.cs is awsome... Moq and PropertyChanged in test method is very useful...

Any way, Great works! Thank you!

**Pull request merged**
