### PR TITLE
Implement Azure LoginService

### PR DESCRIPTION
**Pull request by runceel**
Implement Azure LoginService #40

### CODE REVIEW

**Comment by runceel** [comment]
Completed!! Please review.

**Comment by runceel** [comment]
change project name to Azure suffics.

**Comment by nuitsjp** [comment]
Do I need to reference the Azure package in these projects?

- BlueMonkey.ExpenceServices
- BlueMonkey.LoginService
- BlueMonkey.Model
- BlueMonkey.TimeService

Debug.WriteLine remains.
Do you consider using Prism's logging?

Https://github.com/ProjectBlueMonkey/BlueMonkey/pull/41/files#diff-b43fa83a24ea1e8a71afa974df8e6b53R54

**Comment by runceel** [comment]
I removed Mobile Apps reference from unneeded projects and erace debug log.

Please ReReview.

**Comment by nuitsjp** [comment]
Please delete similar libraries added by setting Microsoft.Azure.Mobile.Client in the same way.

- Microsoft.Bcl
- Microsoft.Bcl.Build
- Microsoft.Net.Http
- Newtonsoft.Json

Do you need the following files?
- BlueMonkey.ExpenceServices.Local / app.config
- BlueMonkey.ExpenceServices / app.config
- BlueMonkey.LoginService.Local / app.config
- BlueMonkey.LoginService / app.config
- BlueMonkey.Model.Tests / app.config
- BlueMonkey.Model / app.config
- BlueMonkey.TimeService.Tests / app.config
- BlueMonkey.TimeService / app.config
- BlueMonkey.ViewModel.Tests / app.config
-

**Comment by runceel** [comment]
Thank you for your review.

I removed reference and app.config.

**Comment by ytabuchi** [comment]
Sorry for late response! I've done! Thank you!!!

**Pull request merged**
