### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by ayasesh**
#65

### CODE REVIEW

**Comment by ayasesh** [comment]
Finish. I coded it in my opinion.
Please review.

**Comment by nuitsjp** [comment]
The top of the list is Jxug good?
Otherwise, it's great.

**Comment by nuitsjp** [comment]
Sorry, one more thing. "Japan Xamarin User Group".

**Comment by ayasesh** [comment]
Is the order important?
I think this order is fine.

**Pull request merged**
