### PR TITLE
start separate directory

### PR DESCRIPTION
**Pull request by runceel**
work in progress...

### CODE REVIEW

**Comment by runceel** [comment]
relative issue #3.

**Comment by runceel** [comment]
How do you do?

**Comment by nuitsjp** [comment]
If we implement the server-side C #, do you think common codes on client-side and server-side.

**Comment by nuitsjp** [comment]
I always do the following.
root
    - Docs
    - Source
       - SolutionA.sln
       - SolutionB.sln
       - ProjectA Directory
       - ProjectB Directory
       - ProjectC Directory

I will put project folders and solution files in the same directory.
If necessary, share the project from different solutions.

**Comment by runceel** [comment]
It looks so good in C# case.
Which do we use node.js or C#?

**Comment by nuitsjp** [comment]
I dont know most of Node.js
But in that case, it seems better to divide in client-side and server-side.

**Comment by runceel** [comment]
Change to folder structure.

Please revew.

**Pull request merged**
